version: "3"

services:

  ################################
  ####     AUTH SERVICE        ###
  ################################

  auth_service:
    container_name: auth_service
    image: ghcr.io/instanvi/app/auth
    ports:
      - "5000:3000"

  ################################
  ####     DSP SERVICE         ###
  ################################

  dsp_service:
    container_name: dsp_service
    image: ghcr.io/instanvi/app/dsp
    ports:
      - "5001:3000"

  ################################
  ####     SSP SERVICE         ###
  ################################


  ssp_service:
      container_name: ssp_service
      image: ghcr.io/instanvi/app/ssp
      ports:
        - "5002:3000"
